version: '3'
services:
  application:
    build:
      context: ../
      dockerfile: ./docker/DockerFile
    image: patterns/cache
    networks:
      - nginx_network
    hostname: application
    ports:
      - "8080:8080"
    container_name: application
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://application:8080/caches/expires" ]
      interval: 30s
      timeout: 10s
      retries: 5
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /data/nginx/cache
    networks:
      - nginx_network
    container_name: nginx
    depends_on:
      - application
networks:
  nginx_network:
    driver: bridge
